/*
====================================================================
View Name: gold_customer_analytics_view.sql
Purpose:
    Create a customer analytics reporting view.

Description:
    - Combines sales and customer data.
    - Calculates customer age and aggregates purchasing behavior.
    - Segments customers by age group and value.
    - Computes recency, lifespan, and spending metrics.
====================================================================
*/

-- Create reporting view
CREATE VIEW gold_report_customer AS

/*
--------------------------------------------------------------------
Step 1: Base Query
    - Join fact and dimension tables
    - Clean data (exclude NULL order dates)
    - Derive customer full name and age
--------------------------------------------------------------------
*/
WITH base_query AS
(
    SELECT 
        f.order_number,
        f.product_key,
        f.order_date,
        f.sales_amount,
        f.quantity,
        c.customer_key,
        c.customer_number,
        
        -- Combine first and last name
        CONCAT(c.first_name, ' ', c.last_name) AS customer_name,
        
        -- Calculate customer age in years
        TIMESTAMPDIFF(YEAR, c.birthdate, CURDATE()) AS age

    FROM 
        gold_fact_sales f

    -- Join sales fact table with customer dimension
    LEFT JOIN
        gold_dim_customers c
        ON f.customer_key = c.customer_key

    -- Remove records with missing order dates
    WHERE 
        f.order_date IS NOT NULL
)

/*
--------------------------------------------------------------------
Step 2: Customer Aggregation
    - Aggregate sales metrics per customer
    - Calculate lifespan and performance indicators
--------------------------------------------------------------------
*/
, customer_aggregation AS
(
    SELECT 
        customer_key,
        customer_number,
        customer_name,
        age,
        
        -- Total number of unique orders
        COUNT(DISTINCT order_number) AS total_orders,
        
        -- Total revenue generated by customer
        SUM(sales_amount) AS total_sales,
        
        -- Total quantity purchased
        SUM(quantity) AS total_quantity,
        
        -- Number of distinct products purchased
        COUNT(DISTINCT product_key) AS total_products,
        
        -- Most recent purchase date
        MAX(order_date) AS last_order_date,
        
        -- Customer lifespan in months
        TIMESTAMPDIFF(MONTH, MIN(order_date), MAX(order_date)) AS lifespan

    FROM base_query
    
    -- Group by customer-level attributes
    GROUP BY
        customer_key,
        customer_number,
        customer_name,
        age
)

/*
--------------------------------------------------------------------
Step 3: Final Customer Report
    - Segment customers by age
    - Classify customer value (VIP, REGULAR, NEW)
    - Calculate recency and derived KPIs
--------------------------------------------------------------------
*/
SELECT 
    customer_key,
    customer_number,
    customer_name,
    age,
    
    -- Categorize customers into age brackets
    CASE 
        WHEN age < 20 THEN 'Under 20'
        WHEN age BETWEEN 20 AND 29 THEN '20-29'
        WHEN age BETWEEN 30 AND 39 THEN '30-39'
        WHEN age BETWEEN 40 AND 49 THEN '40-49'
        ELSE '50 and ABOVE'
    END AS age_group,
    
    -- Customer segmentation based on lifespan and spending
    CASE 
        WHEN lifespan >= 12 AND total_sales > 5000 THEN 'VIP'
        WHEN lifespan >= 12 AND total_sales <= 5000 THEN 'REGULAR'
        ELSE 'NEW'
    END AS customer_segment,
    
    -- Most recent order date
    last_order_date,
    
    -- Recency: months since last purchase
    TIMESTAMPDIFF(MONTH, last_order_date, CURDATE()) AS recency,
    
    total_orders,
    total_sales,
    total_quantity,
    total_products,
    lifespan,
    
    -- Average Order Value (AOV)
    CASE 
        WHEN total_sales = 0 THEN 0
        ELSE ROUND((total_sales / total_orders), 2)
    END AS average_order_value,
    
    -- Average Monthly Spending
    CASE 
        WHEN lifespan = 0 THEN '0'
        ELSE ROUND((total_sales / lifespan), 2)
    END AS average_monthly_spending

FROM customer_aggregation;